### ISSUE TITLE
16_prelab cel-data folder is empty

### ISSUE THREAD

**Issue by radlinsky** [greenelab/GCB535#106]
The pre-lab makes it sound like 'cel-data' should be a folder with stuff in it?

**Comment by radlinsky** [comment]
Or is the pre-lab simply an illustrative example of a pipeline, and there isn't any real data ? (the cake is a lie?)

**Comment by cgreene** [comment]
@bvoight : looks like maybe the cel-data symlink is wrong?

Here's where it goes to: `../16_Data_GeneExpression-I/cel-data/`

However, it looks like the folder is now called:
`../16-18_Data_GeneExpression/cel-data`

Not sure if we can fix this after the push.
