### ISSUE TITLE
read.table / read.annotateddataframe confusion in gene expression #1

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#108]
The prelab shows read.table before the annotated data frame. Quite a few people are experiencing confusion at the pData step because of this. Maybe we should get them to read their table first to look at it before the annotated data frame. This would more closely parallel the prelab.

**Comment by bvoight** [comment]
The pre-lab-I is bugged. It should be read.annotateddataframe there; I missed that. My bad.

**Comment by bvoight** [comment]
Fixed.
