### ISSUE TITLE
Pharmacology 1st question

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#114]
It's not clear what the maximum or minimum is referring to. It should be made more clear that it's just maximum or minimum fluorescence with respect to this specific array/experiment. It reads like maximum or minimum control is some universal definition, where maximum is where the cell is different than the background cells.

**Comment by cgreene** [comment]
Let's modify:
`Remember: the use of term "maximum" (control) indicates when the assay from the well returns a response, whereas 'minimum' (control) reflects simply the background noise from the assay (i.e., no response).`
to state:
`Remember: the use of term "maximum" (control) indicates fluorescing cells, whereas 'minimum' (control) reflects background fluorescence in the absence of cells (i.e., no response).`
