### ISSUE TITLE
Pharmacology: check "myplate_zscore" vs "myplate_zscores"

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#115]
make sure the use of this variable is consistently listed (plural vs. not) throughout the assignment.

**Comment by ksiewert** [comment]
Also, for question 8b, make sure that 'z prime factor' is specified, not just 'z-factor'.

**Comment by ksiewert** [comment]
Also, since they haven't learned about dictionaries or look-ups yet, question 3c is a bit tricky.
