### ISSUE TITLE
Ask SMC to update sklearn for 2018 Class

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#117]

**Comment by cgreene** [comment]
Current version is 0.17. We don't want to update now since ML-II has already been assigned. We should ask for an update to the current version next year. This will involve some minor changes in the exercises.

**Comment by gwaygenomics** [comment]
Ran into related issue when addressing #143 on line 176 of  file `30_ML-III/ML_3_Inclass_Homework.ipynb`. We will need to check the version and ask `CoCalc` to update if necessary. Also, [version 19 was released this summer](http://scikit-learn.org/stable/whats_new.html#version-0-19).

**Comment by cgreene** [comment]
This connects to #155

**Comment by gwaygenomics** [comment]
```
~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> sklearn.__version__
'0.19.0'
```
