### ISSUE TITLE
Python V isinstance

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#120]
The isinstance optional part is very convoluted, and is not the way that it would actually be done. This assignment already seems pretty difficult, so I think we can just delete the optional part.

In addition, I would add an example to the prelab where there is a function with no inputs, so it's similar to ask_input in the assignment.

**Comment by gwaygenomics** [comment]
Related to #121

**Comment by gwaygenomics** [comment]
> The isinstance optional part is very convoluted, and is not the way that it would actually be done. This assignment already seems pretty difficult, so I think we can just delete the optional part.

I agree. Will be deleted in next PR
