### ISSUE TITLE
Variation I: Plink data file path

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#130]
Change plink_lab to 33_Data_Variation-I in part I. Also, for some reason the file was already unzipped, so we should zip it back up.

**Comment by ksiewert** [comment]
Also, the coordinates in the plink file are hg18, so for Q11, tell them to use the rs number, not the coordinate to find the nearest gene.

**Comment by gwaygenomics** [comment]
> Also, the coordinates in the plink file are hg18, so for Q11, tell them to use the rs number, not the coordinate to find the nearest gene.

This is also discussed in #131

**Comment by cgreene** [comment]
- [ ] Removed unzipped / results files.
- [ ] Telling the students to CD to the Data directory.
- [ ] Revised Q11
- [ ] Specified hg18
