### ISSUE TITLE
Variation-II

### ISSUE THREAD

**Issue by kelsj** [greenelab/GCB535#136]
In section 3, the .mds file name they are told to use is wrong. Should be malmo_v4_mds.mds throughout.

**Comment by gwaygenomics** [comment]
I can't seem to find this error, nor a [commit in history](https://github.com/greenelab/GCB535/commits/976709cfbb240fe7ecfbd286d7f481d4635a051a/34_Variation-II/34_Analysis_of_Genetic_Variation_II_inclass.ipynb) that would indicate that its been fixed.

Am I looking at the right file for this? `34_Variation-II/34_Analysis_of_Genetic_Variation_II_inclass.ipynb`? @kelsj

**Comment by gwaygenomics** [comment]
Oh, perhaps, in section 3 `malmo_v3_indcln.mds` should be `malmo_v4_mds.mds`. Is that a correct interpretation?

**Comment by gwaygenomics** [comment]
Also, is #134 a duplicate issue?
