### ISSUE TITLE
Include link to Sarah's original python materials

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#139]
I got feedback from one the students wishing there was more coverage of basic python concepts. I really like Sarah's python bootcamp materials (which is what the modules are based off of), so we might as well link to them at some point. They go more in depth than we had space to go in just a few modules. The link is https://github.com/sarahmid/programming-bootcamp

**Comment by gwaygenomics** [comment]
I believe that most of the materials in @sarahmid's repository are being ported to https://github.com/PennGCB/python_bootcamp 

Once this is complete, I can update the [README](https://github.com/greenelab/GCB535#python-programming-exercises) and close this issue
