### ISSUE TITLE
R/Bioconductor/Gene Expression

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#15]
- in prelab, make clear that the example-pheno.csv is actually a file that you have to create (and that the code will simply report what is in the file)
- The prelab doesn’t have quotes around the array name, so bioconductor doesn’t know that it should be a string. (## this is the sectino where I draw annotation packages for my array from bioconductor)
- clarify that they don’t need to biocLite the annotation library in sagemathcloud
- issues with folks using RStudio and not having permissions to install libraries
- clarify in prelab that that do not need to make a new directory to store data
- check the use of nano in creation of files (control characters are annoying from sagemathcloud)
- make sure to emphasize that capital letters matter, e.g. eBayes is not ebayes; topTable is not toptable and that you will get massively different results depending on the function you use.

**Comment by bvoight** [comment]
Done
