### ISSUE TITLE
syllabus

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#154]
better define what a project is + work / ingenuity required

**Comment by gwaygenomics** [comment]
linked with #142

**Comment by cgreene** [comment]
I think this was something @kelsj said during our meeting. @kelsj : what were you thinking here?

**Comment by bvoight** [comment]
Kelsey said it was more to do with master's students. Perhaps I'll make a set of examples in the 'course project' description about "ingenuity" to make this clear.

**Comment by bvoight** [comment]
Updated for 2019

Need to confirm room and time with Camie (she was out on the bug fix day)

**Comment by bvoight** [comment]
Office hours room is set - hopefully TAs can make it work
