### ISSUE TITLE
R/Bioconductor/Annotations

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#16]
- Add detail on the use of the merge() function in the prelab
- Add more details on the last question about what we’re looking for. How many significant enrichments should they list? When looking for duplicates, should they just tell you the names of the genes that are duplicated, or also the number of times they’re duplicated. Also, just having a brief explanation of this tool in the pre-lab would be very helpful.

In general, 12/13 were hard for students. They needed an extra day for it. Maybe reorganize, give some of the easier assignments first

**Comment by bvoight** [comment]
Need to revamp as R
Need to add data download to 16_DATA directory.

**Comment by bvoight** [comment]
Done.
