### ISSUE TITLE
Motif III: Clarify what is "an unnecessary file" for the homework

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#172]
At the beginning of the homework, the students are asked to "remove unnecessary files" from their homework before they submit.

But it's not clear what is "unnecessary"

we might change this to be very *specific* about what to remove -- perhaps even a specific command that they run (execute) at the end to 'clean things up'
or specifically tell them what to remove per each command they run

**Comment by zhouzilu** [comment]
Issue fixed
