### ISSUE TITLE
ENCODE file downloads

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#174]
Ophir noticed when going through file updates that it looks like ENCODE has pulled/archived a bunch of data (including the files we were using) -- it could be that they are changing builds (to hg38), but perhaps something more complex (where they may be recalling a large number of things)

**Comment by jingyaq** [comment]
For whatever reason it is not easy to search for file names on ENCODE, so I swapped all the file IDs out for experiment IDs and made a note to link out to GEO. Specified that they should be downloading broad peaks or replicated peak files - it's unclear if these are the same files we've used in previous years, we might need to update the answers accordingly.
