### ISSUE TITLE
ENCODE-II: says mm9, but files available are mm10

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#180]
I don't think it *actually* matters since in this assignment, the students are downloading files (presumably each of which is mapped to the same build consistently), and then running intersect

But earlier, they are looking at mm9 so that at first blush was a little bit confusing.

The actual numbers for the intersect might differ for grading purposes, so something to check

**Comment by genestats** [comment]
@ cgreene - not yet - will close asap
