### ISSUE TITLE
GeneExpression (I,II): Spec of Phenotype file, extra cel files, "appropriate" cel files

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#188]
Some banter about what in the document constitutes "appropriate" (this could be a little bit more clear to say "only files that you want to analyze"). it's true we want them to struggle with the file and select the files that are appropriate, so maybe worth adding some leading questions about which files to use, how many files there should be, and that the phenotype file should have 8 entries (not 12).

**Comment by kelsj** [comment]
Currently grading this assignment. I think they could use a reminder or more clear statement about which samples to use/compare. Quite a few students are including all 12 samples in their phenotype file.

**Comment by zhouzilu** [comment]
Issue fixed.
