### ISSUE TITLE
Pharmacology

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#19]
- It is confusing to refer to the maximum controls as positive, and the minimum controls as negative, when the maximum controls are not the ones with the signal that we care about. Probably want to get rid of this notation, and make clear the hypothesis we are testing.
- as.numeric doesn’t work. Want to use *1 or +1 instead
- Reword the last homework question. We received several questions asking what the third bullet point was asking for. Also, the students haven’t learned about dictionaries in R, so it wasn’t immediately clear to them what they should be using.

**Comment by bvoight** [comment]
Updated.

Removed references to positive/negative controls. 
Added a question to make it clear what max/min controls refers to in the assay
fixed as.numeric reference
Revised last homework question to remove references to python, ask students to describe in human words how they would perform the lookup (not using dictionaries, obviously that's faster, but the goal of the homework is to get them to talk out loud about what they would do, before they code).
