### ISSUE TITLE
Gene Expression III: are there actually NA entries in this list? 

### ISSUE THREAD

**Issue by bvoight** [greenelab/GCB535#190]
When the students are asked the question about unique genes in the list, previous version of the annotation file had "NA"s present; in looking back at this, I think there may NOT be NAs (due to updates) but "blank" entries instead. probably want to make sure they "check" both things and filter?

**Comment by zhouzilu** [comment]
This issue has been handled. When I look at the Q9 of Expression III, the hint goes:
"
TIP: Think through (in human terms) the specific tasks/function calls you will need to do perform the task.
Create a variable called "uniqgenelist" that lists your mgi gene symbols. (Hint: Use the variable "tt_annot_s".)
Double check the list of genes that you have constructed. Do all of the entries have a gene listed?
Create a new variable called "uniqgenelist_filt" that excludes entries that are "NA" or are empty (i.e., "").
Hint #2: length(), unique(), and is.na() functions may be useful to you.
Hint #3: the "!" (she-bang) character computes ths inverse of the function. e.g. "!is.na(list)" means in human terms "which elements in list are NOT NA?"
Hint #4: you can use logical operations (i.e., ==, !=) to match 'empty' entries (i.e., ""), even within []. Try it!
"
This includes both NA and empty entries. When I run the pipeline again, there is only 1 NA entry and 0 empty entry. So, the student might have made a mistake in the previous steps.

I will close this for now.
