### ISSUE TITLE
CHIP-Seq I

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#20]
* Should have a big red message above the bowtie command saying not to run it, because if they try to, it will overwrite the sam file!
* The question about why the peak covers a larger window than seems to be supported by raw reads is pretty ambiguous, and because they didn’t read the MACS paper it might not be entirely reasonable
* In the third paragraph under 'Step 3: Peak calling (sam/bam -> bed)', I wrote that we generate the file 'p53-input.DMSO_peaks.bed'. This is a typo from when I was writing the material, the file is actually called 'p53-input.DMSO_peaks.narrowPeak'.
* The question about ‘bumps’ is pretty ambiguously worded, should be reworded or taken out

**Comment by alexamlie** [comment]
I addressed these concerns; I got rid of the question about 'bumps' and changed the question about the raw reads to be more open ended to just ask whether those patterns seem to support the peak or not, and redistributed the points across the other questions to make up for the points
