### ISSUE TITLE
CHIP-Seq II

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#21]
- When the bedGraph files are uploaded to the genome browser, they all have the same name, so you have to change the name yourself in order to compare all 4 of the data sets. We should put a track definition line in the bedGraph files. 
- Questions 1 and 2 are sort of confusing since they seem to be asking the same thing, so it should be clearer what we’re looking for (question 1 is where in the gene the bedGraph files are and question 2 is about the actual called peaks).

**Comment by alexamlie** [comment]
I addressed these issues; I tried to be clearer with question 1 referring to the bedGraph files and question 2 referring to the narrowPeak files
