### ISSUE TITLE
Unix II: Link to data file is broken

### ISSUE THREAD

**Issue by jingyaq** [greenelab/GCB535#212]
Got an email saying the ChIP-seq data link (http://tesla.pcbi.upenn.edu/~alexaml/roadmap_chromosomal_cov.tar.gz) isn't working. Need to get the right file path

**Comment by jingyaq** [comment]
File now at: http://inferno.lisanwanglab.org/roadmap_chromosomal_cov.tar.gz
Move this off Alex's web page for 2020

**Comment by cgreene** [comment]
In https://github.com/greenelab/GCB535/commit/58fddd533ad6a8400b335d862d9e921455a59455 I made this use GitHub as the host. 🤞 that it doesn't break now!
