### ISSUE TITLE
Motif 1

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#24]
Questions about relative entropy vs entropy for motifs, and the relationship between information content. This is pretty confusing and not clear: information content is opposite of entropy, but typically linked with relative entropy (but not necessarily)

**Comment by alexamlie** [comment]
I tried to add some clarifying sentences in section 3 of this notebook to give more of an intuition about relative entropy, but I'm not sure if there's a better way to do this (so I leave it open for now)
