### ISSUE TITLE
ML Assignments

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#34]
It was difficult to grade these because there weren't concrete problems for them to answer. I think this also caused some of the students to not spend much time on them, and others felt confused because they weren't sure exactly what they were supposed to be doing. So maybe next year it would be better to have the assignments in the same Q/A format as most of the other assignments?

**Comment by cgreene** [comment]
Direct students more to what they are supposed to be learning and trying.

**Comment by cgreene** [comment]
Concrete problems added. e11896c wraps up this series of changes.
