### ISSUE TITLE
Data Folders

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#60]
One of the things that we learned is that anything in an assignment folder that gets collected fills up our overall course space with n_students \* size when we collect. We should take larger data files and put them in a directory such as `##_Data_Name` analogous to what we've done with `Prelab` materials. This gets assigned to the students but not collected.

Here is the current output of `du -hs * | sort -hr`

213M    09_ChIP-Seq-II
109M    16_Prelab_GeneExpression-I
97M 29_ML-II
51M 34_Data_Variation-II
45M 33_Variation-I
39M 31_ML-IV
29M 30_ML-III
16M 32_ML-V
15M WHATAMI_Motif-III-temp
5.6M    30_Prelab_ML-III
5.2M    33_Prelab_Variation-I
4.6M    08_ChIP-Seq-I
2.8M    SETUP_UNIX_I
2.4M    11_Prelab_ENCODE-I
1.9M    26_Python-IV
1.8M    12_Prelab_ENCODE-II
1.3M    06_Motif-III
1.2M    02_Prelab_Unix-I
1.1M    SETUP_UNIX_II
576K    19_Prelab_RNA-Seq-I
500K    19_RNA-Seq-I
296K    15_Reproducibility
264K    15_Prelab_Reproducibility
192K    03_Prelab_Unix-II
152K    24_Python-II
152K    22_Pharmacology
116K    05_Motif-II
84K 02_UNIX-I
64K 13_Prelab_R-I
56K 13_R-I
56K 11_ENCODE-I
52K 26_Prelab_Python-IV
52K 14_R-II
48K 14_Prelab_R-II
44K 24_Prelab_Python-II
44K 23_Python-I
44K 23_Prelab_Python-I
40K 25_Prelab_Python-III
40K 04_Motif-I
36K 28_ML-I
36K 25_Python-III
28K 10_Phylogenies
28K 07_Alignment
24K 12_ENCODE-II
24K 01_Databases
20K 34_Variation-II
20K 03_Unix-II
16K 17_Prelab_GeneExpression-II
16K 07_Prelab_Alignment
12K 29_Prelab_ML-II
12K 17_GeneExpression-II
12K 16_GeneExpression-I
8.0K    Syllabus.md
8.0K    Course_Calendar.md
8.0K    28_Prelab_ML-I
8.0K    10_Prelab_Phylogenies
8.0K    00_Sagemathcloud
4.0K    README.md
4.0K    LICENSE
4.0K    34_Prelab_Variation-II
4.0K    32_Prelab_ML-V
4.0K    31_Prelab_ML-IV
4.0K    27_Python-V
4.0K    27_Prelab_Python-V
4.0K    22_Prelab_Pharmacology
4.0K    21_RNA-Seq-III
4.0K    21_Prelab_RNA-Seq-III
4.0K    20_RNA-Seq-II
4.0K    20_Prelab_RNA-Seq-II
4.0K    18_Prelab_GeneExpression-III
4.0K    18_GeneExpression-III
4.0K    09_Prelab_ChIP-Seq-II
4.0K    08_Prelab_ChIP-Seq-I
4.0K    06_Prelab_Motif-III
4.0K    05_Prelab_Motif-I
4.0K    04_Prelab_Motif-I
4.0K    01_Prelab_Databases
0   Office_Hours.md

**Comment by cgreene** [comment]
with the recent commits, everything other than `16_Prelab_GeneExpression-I` has been moved to a `_Data_` folder.

213M	09_Data_ChIP-Seq-II
109M	16_Prelab_GeneExpression-I
97M	29_Data_ML-II
51M	34_Data_Variation-II
45M	33_Data_Variation-I
39M	31_Data_ML-IV
29M	30_Data_ML-III
15M	WHATAMI_Motif-III-temp
9.6M	32_Data_ML-V
6.2M	32_ML-V
5.6M	30_Prelab_ML-III
5.2M	33_Prelab_Variation-I
4.6M	08_ChIP-Seq-I
2.8M	SETUP_UNIX_I
2.4M	11_Prelab_ENCODE-I
1.9M	26_Python-IV
1.8M	12_Prelab_ENCODE-II
1.3M	06_Motif-III
1.2M	02_Prelab_Unix-I
1.1M	SETUP_UNIX_II
576K	19_Prelab_RNA-Seq-I
500K	19_RNA-Seq-I
296K	15_Reproducibility
264K	15_Prelab_Reproducibility
204K	33_Variation-I
192K	03_Prelab_Unix-II
152K	24_Python-II
152K	22_Pharmacology
124K	29_ML-II
116K	05_Motif-II
84K	02_UNIX-I
64K	13_Prelab_R-I
56K	13_R-I
56K	11_ENCODE-I
52K	26_Prelab_Python-IV
52K	14_R-II
48K	14_Prelab_R-II
44K	24_Prelab_Python-II
44K	23_Python-I
44K	23_Prelab_Python-I
40K	25_Prelab_Python-III
40K	04_Motif-I
36K	28_ML-I
36K	25_Python-III
28K	10_Phylogenies
28K	07_Alignment
24K	12_ENCODE-II
24K	09_ChIP-Seq-II
24K	01_Databases
20K	34_Variation-II
20K	03_Unix-II
16K	17_Prelab_GeneExpression-II
16K	07_Prelab_Alignment
12K	30_ML-III
12K	29_Prelab_ML-II
12K	17_GeneExpression-II
12K	16_GeneExpression-I
8.0K	Syllabus.md
8.0K	Course_Calendar.md
8.0K	31_ML-IV
8.0K	28_Prelab_ML-I
8.0K	10_Prelab_Phylogenies
8.0K	00_Sagemathcloud
4.0K	README.md
4.0K	LICENSE
4.0K	34_Prelab_Variation-II
4.0K	32_Prelab_ML-V
4.0K	31_Prelab_ML-IV
4.0K	27_Python-V
4.0K	27_Prelab_Python-V
4.0K	22_Prelab_Pharmacology
4.0K	21_RNA-Seq-III
4.0K	21_Prelab_RNA-Seq-III
4.0K	20_RNA-Seq-II
4.0K	20_Prelab_RNA-Seq-II
4.0K	18_Prelab_GeneExpression-III
4.0K	18_GeneExpression-III
4.0K	09_Prelab_ChIP-Seq-II
4.0K	08_Prelab_ChIP-Seq-I
4.0K	06_Prelab_Motif-III
4.0K	05_Prelab_Motif-I
4.0K	04_Prelab_Motif-I
4.0K	01_Prelab_Databases
0	Office_Hours.md

**Comment by cgreene** [comment]
Only 16 gene expression is left. @bvoight

**Comment by cgreene** [comment]
removed myself since only expression is left

**Comment by bvoight** [comment]
Think this is set up. However, I will need to change the way the assignment works such that students install their data into the 16_DATA directory
