### ISSUE TITLE
Make sure Canvas Name matches SageMathCloud name

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#65]
Have students register on SMC with the same last name (different first name is fine) that they use on Canvas. If they don't, then the grading sheet format we need for canvas will not be in the same order as the students on SMC, and it's a pain in the butt and leads to transcription errors.

I don't know who this should be assigned to. Maybe whoever is doing the intro to the course?

**Comment by bvoight** [comment]
I have mentioned this in the intro on the first day of class.
