### ISSUE TITLE
Where to introduce ipython notebooks

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#67]
Right now, the introduction to how to use juypter notebooks is in the prelab to Python I. Since we'll be using jupyter notebooks way before we reach that section of the course, should we move it to one of the first classes? 
The python prelab also talks about things like "what is a program". Should this be moved to the first module on R?

**Comment by cgreene** [comment]
@ksiewert : I agree that we need to introduce jupyter notebooks - what about on the first/database day @bvoight?

Side note: can we switch the R ones from sage worksheets (or whatever we used last time) to jupyter notebooks? I'm not sure if this is tough or easy, but it'd be nice to have a single format.

I think we need "what is a program" moved to the first R module.

**Comment by bvoight** [comment]
I've added an intro to SMC and ipython NB to the first day's lecture.
I'm going to close, and reopen the two additional issues brought up here (add "what is a program" to first R module; and switching sage worksheets to R notebooks)
