### ISSUE TITLE
chipseq 2 sagemath cloud memory issues

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#91]
We had to, at the last minute, make a Data2 directory. We then distributed the results of running four commands.

SageMathCloud limits student accounts to less memory than the instructor account. This step takes ~1-2 minutes and uses ~2-4GB of RAM when it is running. There does not appear to be a great way to handle this workflow given the current billing options available and the 60 students in our class (need for ~240GB of RAM for ~10 minutes during the term of the course).

Maybe @williamstein has a tip for how we might address this in the future.

**Comment by williamstein** [comment]
Unfortunately, this is technically very difficult  for us to deal with on the backend right now.    On the bright side, we spent July-Sept last year writing a new Kubernetes-based backend, which would make this very easy for us to address... but it is not ready yet (it's a major switch).

**Comment by cgreene** [comment]
@williamstein : Is there a way that we can store a log of how much memory gets used during a series of steps (e.g. when our TAs run the analysis before the students to check the steps)? This would help us quickly predict when issues will arise for us in practice so that we can develop a workaround in advance of our in class experiences.

**Comment by williamstein** [comment]
This Python function will give the total memory usage by the entire project (as a string... look at smem docs?):
```
def mem():
    return os.popen('smem -ntk').read().split()[-1]
```

You can call it periodically and see what's used.

**Comment by cgreene** [comment]
Hi @williamstein : did any of these architecture changes make it in? We're starting to prepare the materials for 2018. Thanks!

**Comment by williamstein** [comment]
One change is that everybody can easily *see* exactly how much memory and CPU their Jupyter notebook is using in an indicator at the top right: 

![screenshot 2017-11-06 at 8 48 15 am](https://user-images.githubusercontent.com/1276278/32452736-40b4c79a-c2cf-11e7-98ea-80b579c3d5eb.png)

We are also considering just changing the course plans to include 2GB of RAM per student instead of 1GB...

But in your case we can easily just sell you an upgrade for 1 day that provides a lot more memory, you can then apply it to the whole course, the day it is needed, etc. - contact us via support.

**Comment by cgreene** [comment]
@williamstein : can you walk me through how we might pay for that? We're going to try to get everything on one bill this year so that reimbursement is easier. It'd be great to be able to pay for something like:

* Nov 2017 -> May 2017 / 1 project internet access + member hosting
* Start Jan 2018 -> End April 2018 ~55 students + memory + disk space + member hosting + internet

All in one chunk 😄 . It looks like we would need slightly different monthly plans for each of these under the current system. Can we pre-pay some of that and activate them at a specific time?

Thanks!

**Comment by williamstein** [comment]
Hi -- we'll create a single unified invoice (one time payment) for you, which includes what you need for the full year...

**Comment by williamstein** [comment]
I sent an email to you; if you don't get it, let me know, as I may have used the wrong address...

**Comment by cgreene** [comment]
Ok - we've got this done. Going to close issue for now! 👍
