### ISSUE TITLE
Samtools version is very old on sagemath cloud

### ISSUE THREAD

**Issue by cgreene** [greenelab/GCB535#92]
The Samtools version on the cloud is old enough that it does not have the help command implemented yet. It looks like 0.1.19 was snagged from the old website. There's a new site for the new version here:
http://www.htslib.org/

This version allows students to access man pages and other help features.

**Comment by gwaygenomics** [comment]
Does SMC (or cocalc) allow for conda kernel integration? I've been happy so far with [conda mgmt of samtools](https://anaconda.org/bioconda/samtools) (and other sequencing pipeline tools too)

**Comment by cgreene** [comment]
Would need to check their docs (and play around with the system). If you can't find it, tagging @williamstein with a specific question has resulted in helpful answers in the past. I just want to make sure we check docs first. 😄

**Comment by williamstein** [comment]
I've seen this, but please make a support request by clicking the "Help" button or email help@sagemath.com, since we're a company with a number of employees, and I almost never do upgrades of general software components.

**Comment by gwaygenomics** [comment]
I submitted a ticket (4648) with this request @williamstein

**Comment by gwaygenomics** [comment]
updated to `1.6`
