### ISSUE TITLE
Make chip-seq II homework directions more clear

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#94]
It's not clear what files they should be using for the bedintersect commands on the homework so I would tell them the file extensions, and reiterate where each file comes from and what it contains.

**Comment by cgreene** [comment]
I was told to assign this to @ksiewert and this might be a thing that she could do for the slice of pizza she already took. WE ARE THE WORST!

**Comment by ksiewert** [comment]
When I was young, we had to make assignments, not just edit them. And we weren't given free pizza.  Y'all are spoiled now.

Tell Ben that I'll do this instead of writing the CAD paper.
