### ISSUE TITLE
ENCODE I reword

### ISSUE THREAD

**Issue by ksiewert** [greenelab/GCB535#96]
The accession number should be next to the data file, not next to the genome file, for clarity. "Click on the data set, then download the bed narrowPeak formatted files in human genome version hg19 (ENCFF001UUH)."

Also, it should say them to run it 5 times, not 10.

Also, maybe a paragraph reiterating what the DNAse/T1D SNP overlap is trying to test. Maybe state it as a null hypothesis.

**Comment by gwaygenomics** [comment]
#98 is a subset of this issue
